#!/bin/bash
cd /home/user/myapp/android
./gradlew --stop
cd /home/user/myapp

rm -rf /home/user/.gradle/daemon
rm -rf /home/user/.gradle/caches/build-cache-1
rm -rf /home/user/.gradle/caches/transforms-*
# +30сек rm -rf /home/user/.gradle/caches/8.12/transforms

# rm -rf ~/.android/cache ~/.androidsdkroot/.installer ~/.androidsdkroot/.temp
# rm -rf /home/user/.gradle/caches/8.12/javaCompile

# вызовет последуюющую очень долгую сборку но реально очистит место
# rm -rf ~/.gradle/caches
# find ~/.gradle/caches -type f -atime +0 -delete




rm -rf /home/user/myapp/build/app/outputs/apk/debug/app-debug.apk
rm -rf /home/user/myapp/build/app/outputs/apk/release/app-release.apk
rm -rf /home/user/myapp/build/app/outputs/flutter-apk/app-debug.apk


# Flutter clean при желании можно оставить
# flutter clean
# flutter pub get

df -h .